### ISSUE TITLE
Draft architecture diagrams

### ISSUE THREAD

**Issue by ghost** [pragma-org/amaru#14]
Having a few architecture diagrams, even as draft or sketch, in place would be quite useful to understand where we are and where we want to go. I found [C4 Model](https://c4model.com/) have the right balance of flexibility and precision.

**Comment by rolas978** [comment]
What do you use to make the diagrams? UML-specific?
Would PlantUML be used in this case?
I found out about it recently, and some of the charts look great.
![image](https://github.com/pragma-org/amaru/assets/46205985/4a634874-8dea-473b-a5eb-967f342f4e89)

this is the guide:
https://plantuml.com/guide

**Comment by abailly-iohk** [comment]
PlantUML is nice, yes. And there's support for C4 style with
```
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
```
