### ISSUE TITLE
Instrument the Cardano Haskell node to start at a specific point.

### ISSUE THREAD

**Issue by KtorZ** [pragma-org/amaru#3]
Either by:

- Forcing a rollback to specifying point by deleting chunks from the immutable db.
- Bootstrapping from a Mithril snapshot.  

Possible, look at the work done as part of Mithril as there might already be tools covering that.

**Comment by abailly-iohk** [comment]
FWIW I have worked a while ago on the part of ouroboros-consensus code that manipulates the DB, writing a tool to dump an arbitrary block in JSON format. I could revive that branch and implement that feature on top of this tool, or adapting/enhancing one of the existing tools (eg. `db-analyzer`?)

**Comment by KtorZ** [comment]
That would be quite handy for benchmarks and tests moving forward. As we will want to compare precise execution paths on both Haskell's cardano-node & Amaru. 

Do you have enough information from this thin ticket or shall we perhaps bring that as a topic on the agenda of a next Amaru design planning session?

**Comment by Dam-CZ** [comment]
Closed and content integrated in the milestone: Client Node - Dolos integration and architecture choices
