### ISSUE TITLE
[EPIC] Middleware integrations

### ISSUE THREAD

**Issue by KtorZ** [pragma-org/amaru#5]
## Tasks

- [x] #15
 
- [ ] Integrate the utxoRPC in [Oura](https://github.com/txpipe/oura) (and transitively Carp)
  - https://github.com/txpipe/oura/issues/763

- [ ] Evaluate gaps for integrating [cardano-db-sync](https://github.com/intersectmbo/cardano-db-sync) with utxoRPC.

## Acceptance Criteria

- Middleware[^1] should be able to synchronize blocks from Dolos/Polaris using the utxoRPC and/or mini-protocols

[^1]: In scope are at least Kupo & Oura. Others to be considered.

**Comment by Dam-CZ** [comment]
Closed - Content added to the milestone : [Partial transaction validation & Relay node](https://github.com/pragma-org/amaru/milestone/3)
